# -*- coding: utf-8 -*-
"""Python para Ciencia de Datos / Manejo de cadenas (Core).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ibvXzDG0ZXuAmNq1DFYdIRgwZtvDkZkh

Tarea: Manejo de cadenas (Core)
Nombre: Luciano Benjamín Recalde Carballo
"""

# Nombre y edad
nombre = input("Por favor, ingresa tu nombre: ")
edad = input("Por favor, ingresa tu edad: ")

# Saludo personalizado
print(f"Hola {nombre}, espero que estés súper bien, tienes {edad} años, eso quiere decir que naciste en {2024-32}.")

nombre_completo = "Luciano Benjamin Recalde Carballo"

# Convertir a mayúsculas
nombre_mayusculas = nombre_completo.upper()
print(f"Nombre en mayúsculas: {nombre_mayusculas}")

# Convertir a minúsculas
nombre_minusculas = nombre_completo.lower()
print(f"Nombre en minúsculas: {nombre_minusculas}")

# Contar el número de letras
numero_letras = len(nombre_completo.replace(" ", ""))
print(f"Número de letras en el nombre: {numero_letras}")

# Reemplazar el primer nombre por otro nombre
nuevo_nombre = nombre_completo.replace("Luciano", "Agustín")
print(f"Nuevo nombre: {nuevo_nombre}")

nombres = input("Ingresa una lista de nombres separados por comas: ")

lista_nombres = nombres.split(",")

# Imprimir cada nombre
for nombre in lista_nombres:
    print(nombre.strip())  # Usamos strip() para eliminar espacios adicionales alrededor de cada nombre